In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


# Tensors

In [6]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [8]:
x = tf.constant([[5,2], [1,3]])
print(x)    # a constant tensor

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


In [9]:
x.numpy()  # we get numpy array value

array([[5, 2],
       [1, 3]], dtype=int32)

In [10]:
print('dtype:', x.dtype)

dtype: <dtype: 'int32'>


In [11]:
print('shape:', x.shape)

shape: (2, 2)


In [12]:
print(tf.ones(shape=(2,1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [13]:
print(tf.zeros(shape=(2,1)))

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [14]:
tf.random.normal(shape=(2,2), mean = 0, stddev = 1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.18074825,  1.4594393 ],
       [ 1.6656796 , -0.5138987 ]], dtype=float32)>

In [15]:
tf.random.uniform(shape = (2,2), minval = 0, maxval = 10, dtype='int32')

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 2],
       [4, 6]], dtype=int32)>

#Variables

In [16]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.8717772,  1.5106703],
       [-1.2261361,  2.417417 ]], dtype=float32)>


In [17]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)

for i in range(2):
  for j in range(2):
    assert a[i,j] == new_value[i,j]

In [18]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)

for i in range(2):
  for j in range(2):
    assert a[i,j] == new_value[i, j] + added_value[i,j]

# Maths in TF

In [20]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))

c = a + b
d = tf.square(c)
e = tf.exp(d)

In [21]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.1789694 , 1.1413801 ],
       [0.16352034, 0.22669613]], dtype=float32)>

In [22]:
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.3899688 , 1.3027484 ],
       [0.0267389 , 0.05139114]], dtype=float32)>

In [23]:
e

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4.0147247, 3.6793954],
       [1.0270996, 1.0527346]], dtype=float32)>

# Computing gradients with GradientTape

In [24]:
a = tf.random.normal(shape=(2, 2))
b = tf.random.normal(shape=(2, 2))

with tf.GradientTape() as tape:
  tape.watch(a)  # watching a tensor
  c = tf.sqrt(tf.square(a) + tf.square(b))
  dc_da = tape.gradient(c, a)
  print(dc_da)

tf.Tensor(
[[-0.90847     0.85888773]
 [ 0.58744246  0.9569273 ]], shape=(2, 2), dtype=float32)


In [25]:
a = tf.Variable(a)

with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a) + tf.square(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-0.90847     0.85888773]
 [ 0.58744246  0.9569273 ]], shape=(2, 2), dtype=float32)


# Computing Higher Order Derivatives by Nesting Tapes

In [27]:
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a) + tf.square(b))
    dc_da = tape.gradient(c, a)
  d2c_da2 = outer_tape.gradient(dc_da, a)
  print(d2c_da2)

tf.Tensor(
[[0.54862905 0.1438863 ]
 [0.25447822 0.05651945]], shape=(2, 2), dtype=float32)
